sudo: required
services:
  - docker
language: bash
script:
# prepare qemu
- sudo apt-get update
- sudo apt-get install -y wget git
- sudo apt-get remove docker-ce
- echo "deb [arch=amd64 trusted=yes] http://ftp.unicamp.br/pub/linuxpatch/ubuntu/14_04/misc/docker-17.04.0-ce-amd64/ trusty main" | sudo tee /etc/apt/sources.list.d/docker-engine.list
- sudo apt-get update
- sudo apt-get install -y docker-engine
- docker run --rm --privileged multiarch/qemu-user-static:register
- wget https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1/qemu-arm-static.tar.gz -O /tmp/qemu-arm-static.tar.gz
- tar zxvf /tmp/qemu-arm-static.tar.gz -C /tmp
# build image
- docker build --volume type=bind,source=/tmp/qemu-arm-static,target=/usr/bin/qemu-arm-static -t dersimn/helloarm:armhf -f Dockerfile.armhf .
# test image
- docker run -v /tmp/qemu-arm-static:/usr/bin/qemu-arm-static dersimn/helloarm:armhf
# push image
- >
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(if [ "$TRAVIS_BRANCH" != "master" ]; then echo ":$TRAVIS_BRANCH" ; fi)
    docker tag dersimn/helloarm:armhf dersimn/helloarm:armhf$TAG
    docker push dersimn/helloarm:armhf$TAG
  fi